name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop-back

  pull_request:
    branches:
      - main
      - develop-back


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permisson for gradlew
        run: |
          cd ./server
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd ./server
          ./gradlew clean build
